# Test image upload
name: Retry release
on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release directory
        run: mkdir ./pdweekly ./pdweeklyzipped

      - name: Download minimal image
        uses: actions/download-artifact@v4
        with:
          name: puredarwin-minimal
          path: ./pdweekly

      - name: Download full image
        uses: actions/download-artifact@v4
        with:
          name: puredarwin
          path: ./pdweekly

      # puredarwin.img is too big
      - name: Compress images
        run: |
          zip -j ./pdweeklyzipped/puredarwin.zip ./pdweekly/puredarwin.img
          zip -j ./pdweeklyzipped/puredarwin-minimal.zip ./pdweekly/puredarwin-minimal.img
          # sanity check rq
          echo pdweekly:
          ls pdweekly/
          echo pdweeklyzipped:
          ls pdweeklyzipped/

      - name: Upload to Releases
        uses: softprops/action-gh-release@v3.0.3
        with:
          files: pdweeklyzipped/*
          tag_name: weekly
          draft: false
          prerelease: true
